title: Meghana Manvitha Venna
description: ML Engineer | Embedded Systems & Medical AI
theme: jekyll-theme-minimal
author: Meghana Manvitha
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme